server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/hello/**
